export enum GameEvents {
  GAME_STARTED = 'GAME_STARTED',
  GAME_ENDED = 'GAME_ENDED',
  ROUND_STARTED = 'ROUND_STARTED',
  ROUND_ENDED = 'ROUND_ENDED',
  PICK_STARTED = 'PICK_STARTED',
  PICK_ENDED = 'PICK_ENDED',
  HAND_OUT_CARDS = 'HAND_OUT_CARDS',
  PLAYER_CARD_PLAYED = 'PLAYER_CARD_PLAYED',
  PLAYED_CARD_PICK = 'PLAYED_CARD_PICK',
}
